project:
  type: website

website:
  title: "DSCI 521: Computing Platforms for Data Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://ubc-mds.github.io/resources_pages/installation_instructions/
        text: Installation Guide

  sidebar:
    logo: MDSlogo.png
    logo-alt: "MDS Logo Image"
    style: "docked"
    search: true
    contents:
      - text: "Lecture 0a: JupyterLab Orientation"
        href: lectures/0-jupyterlab-orientation-intro.qmd
      - text: "Lecture 0b: RStudio Orientation"
        href: lectures/0-rstudio-orientation-intro.qmd
      - text: "Lecture 1: Introduction to MDS software and Bash"
        href: lectures/1-MDStools-bash-filesystem.qmd
      - text: "Lecture 2: Introduction to version control with Git and GitHub"
        href: lectures/2-git-github-ssh-basic-workflow.qmd
      - text: "Lecture 3: Getting grovy with Git and GitHub"
        href: lectures/3-git-history-merge-conflicts-stash.qmd
      - text: "Lecture 4: Introduction to Quarto and Github Pages"
        href: lectures/4-quarto_github_pages.qmd
      - text: "Lecture 5: Dynamic documents: from markdown to Rmarkdown documents"
        href: lectures/5-rstudio-projects-notebooks.qmd
      - text: "Lecture 6: Quarto, RMarkdown, and Jupyter Slides"
        href: lectures/6-rmarkdown-quarto-slides-ghpages.qmd
      - text: "Lecture 7: Virtual environments"
        href: lectures/7-virtual-environments.qmd
      - text: "Lecture 8: Organization of Data Science projects and some useful tools"
        href: lectures/8-regex-filenames-project-organization.qmd


format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [slate, styles.scss]
    toc: true
    toc-depth: 3
    toc-expand: 3

editor:
  render-on-save: true
  markdown:
    wrap: sentence
