project:
  type: website
  preview:
    port: 54321
    browser: true
  render:
    - "./*.qmd"
    - "*/*.qmd"
    - "lectures/demos/slides/*.qmd"

website:
  title: "DSCI 521: Computing Platforms for Data Science"
  site-url: https://ubc-mds.github.io/DSCI_521_platforms-dsci_book/
  issue-url: https://github.com/UBC-MDS/DSCI_521_platforms-dsci_book/issues/new
  repo-actions: [edit, source, issue]
  google-analytics: "G-1RNLL8GPXK"
  open-graph: true
  twitter-card: true
  page-navigation: true
  bread-crumbs: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    right:
      - icon: github
        href: https://github.com/UBC-MDS/DSCI_521_platforms-dsci_book
        aria-label: GitHub
    left:
      - href: index.qmd
        text: Home
      - href: https://ubc-mds.github.io/resources_pages/installation_instructions/
        text: Installation Guide

  sidebar:
    logo: MDSlogo.png
    logo-alt: "MDS Logo Image"
    style: "docked"
    search: true
    contents:

      - section: "Orientation"
        contents:
          - text: "JupyterLab Orientation"
            href: lectures/0-jupyterlab-orientation-intro.qmd
          - text: "RStudio Orientation"
            href: lectures/0-rstudio-orientation-intro.qmd

      - section: "Week 1"
        contents:
          - text: "MDS Software and Bash"
            href: lectures/1-MDStools-bash-filesystem.qmd

          - text: "Git, GitHub, and SSH"
            href: lectures/2-git-github-ssh-basic-workflow.qmd

      - section: "Week 2"
        contents:
          - text: "Quarto and GitHub Pages"
            href: lectures/4-quarto_github_pages.qmd

          - text: "Quarto, RMarkdown, and Jupyter Slides"
            href: lectures/6-rmarkdown-quarto-slides-ghpages.qmd

      - section: "Week 3"
        contents:
          - text: "Git: History, Conflicts, and Ignores"
            href: lectures/3-git-history-merge-conflicts-stash.qmd

          - text: "RStudio Projects and Literate Programming"
            href: lectures/5-rstudio-projects-notebooks.qmd

      - section: "Week 4"
        contents:
          - text: "Virtual Environments: uv"
            href: lectures/7a-virtual-environments-uv.qmd

          - text: "Virtual Environments: renv"
            href: lectures/7b-virtual-environments-renv.qmd

          - text: "Organization of Data Science Projects"
            href: lectures/8-regex-filenames-project-organization.qmd
          - text: "Introduction to Regular Expressions (RegEx)"
            href: lectures/8b-regex.qmd
          - text: "Asking Effective Questions"
            href: lectures/8c-asking_questions.qmd

      - section: "Additional Information"
        contents:
          - text: "Git Configuration"
            href: appendix/git_config.qmd
          - text: "RStudio Configuration"
            href: appendix/rstudio_config.qmd
          - text: "Semantic Line Breaks"
            href: appendix/semantic_line_breaks.qmd
          - text: "R Markdown tips"
            href: appendix/rmarkdown_tips.qmd

      - section: "Older Materials"
        contents:
          - text: "Xaringan Slides"
            href: appendix/xaringan_slides.qmd
          - text: "Virtual Environments: conda"
            href: appendix/7a-virtual-environments-conda.qmd
          - text: "MDS Conda Python Environment"
            href: appendix/mds_conda_environment.qmd

format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [slate, styles.scss]
    toc: true
    toc-depth: 3
    toc-expand: 3

editor:
  render-on-save: true
  markdown:
    wrap: sentence
