project:
  type: website

website:
  title: "DSCI 521: Computing Platforms for Data Science"
  navbar:
    left:
      - href: index.qmd
        text: Home

  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Lecture 0: JupyterLab Orientation"
        href: lectures/0-jupyterlab-orientation-intro.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor:
  markdown:
    wrap: sentence
