project:
  type: website

website:
  title: "DSCI 521: Computing Platforms for Data Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://ubc-mds.github.io/resources_pages/installation_instructions/
        text: Installation Guide

  sidebar:
    logo: MDSlogo.png
    logo-alt: "MDS Logo Image"
    style: "docked"
    search: true
    contents:

      - section: "Orientation"
        contents:
          - text: "Lecture 0a: JupyterLab Orientation"
            href: lectures/0-jupyterlab-orientation-intro.qmd
          - text: "Lecture 0b: RStudio Orientation"
            href: lectures/0-rstudio-orientation-intro.qmd

      - section: "Lectures"
        contents:
          - text: "Lecture 1: Introduction to MDS software and Bash"
            href: lectures/1-MDStools-bash-filesystem.qmd

          - text: "Lecture 2: Introduction to version control with Git and GitHub"
            href: lectures/2-git-github-ssh-basic-workflow.qmd

          - text: "Lecture 3: Git: History, Conflicts, and Ignores"
            href: lectures/3-git-history-merge-conflicts-stash.qmd

          - text: "Lecture 4: Introduction to Quarto and Github Pages"
            href: lectures/4-quarto_github_pages.qmd

          - text: "Lecture 5: RStudio Projects and Literate Programming Documents"
            href: lectures/5-rstudio-projects-notebooks.qmd

          - text: "Lecture 6: Quarto, RMarkdown, and Jupyter Slides"
            href: lectures/6-rmarkdown-quarto-slides-ghpages.qmd

          - text: "Lecture 7a: Virtual environments: conda"
            href: lectures/7a-virtual-environments-conda.qmd
          - text: "Lecture 7b: Virtual environments: renv"
            href: lectures/7b-virtual-environments-renv.qmd

          - text: "Lecture 8a: Organization of Data Science projects"
            href: lectures/8-regex-filenames-project-organization.qmd
          - text: "Lecture 8b: Introduction to Regular Expressions (RegEx)"
            href: lectures/8b-regex.qmd

      - section: "Appendix"
        contents:
          - text: "Git Configuration"
            href: appendix/git_config.qmd
          - text: "RStudio Configuration"
            href: appendix/rstudio_config.qmd
          - text: "Semantic Line Breaks"
            href: appendix/semantic_line_breaks.qmd

format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [slate, styles.scss]
    toc: true
    toc-depth: 3
    toc-expand: 3

editor:
  render-on-save: true
  markdown:
    wrap: sentence
