---
title: "DSCI 521: Computing Platforms for Data Science"
---

How to install, maintain, and use the data scientific software "stack". The Unix operating system, integrated development environments, and problem solving strategies.

## Course Learning Objectives

- Use the Unix command line to navigate their computer's filesystem.
- Define and distinguish between absolute file paths and relative file paths.
- Effectively use local and remote version control software
  (e.g., Git and GitHub) to organize projects and manage file versions.
- Create, edit and run reproducible literate Python and R code documents
  (e.g., reports and presentations) using Jupyter and RMarkdown.
- Write and edit Markdown and in-line LaTeX syntax within literate code documents.
- Define and correctly use a project working directory.
- Diagnose and troubleshoot programming and development environment problems,
  and explain how such problems can be avoided.

## Lesson Learning Objectives and Readings

Learning objectives are grouped by week.
Some weeks split one set of objectives across several lessons,
and some lessons carry more than one set.

### Orientation

**[JupyterLab Orientation](lectures/0-jupyterlab-orientation-intro.qmd)**

{{< include learning_objectives/lo-ch-00.qmd >}}

**[RStudio Orientation](lectures/0-rstudio-orientation-intro.qmd)**

{{< include learning_objectives/lo-ch-00-rstudio.qmd >}}

**[Positron Orientation](lectures/0-positron-orientation-intro.qmd)**

{{< include learning_objectives/lo-ch-00-positron.qmd >}}

### Week 1

**[MDS Software and Bash](lectures/1-MDStools-bash-filesystem.qmd)**

{{< include learning_objectives/lo-ch-01.qmd >}}

**[Git, GitHub, and SSH](lectures/2-git-github-ssh-basic-workflow.qmd)**

{{< include learning_objectives/lo-ch-02.qmd >}}

**Readings**

{{< include readings/readings-ch-01.qmd >}}

{{< include readings/readings-ch-02.qmd >}}

### Week 2

**[Quarto and GitHub Pages](lectures/4-quarto_github_pages.qmd)**

{{< include learning_objectives/lo-ch-04.qmd >}}

**[Quarto, RMarkdown, and Jupyter Slides](lectures/6-rmarkdown-quarto-slides-ghpages.qmd)**

{{< include learning_objectives/lo-ch-06.qmd >}}

**Readings**

{{< include readings/readings-ch-04.qmd >}}

{{< include readings/readings-ch-06.qmd >}}

### Week 3

**[Git: History, Conflicts, and Ignores](lectures/3-git-history-merge-conflicts-stash.qmd)**

{{< include learning_objectives/lo-ch-03.qmd >}}

**[RStudio Projects and Literate Programming](lectures/5-rstudio-projects-notebooks.qmd)**

{{< include learning_objectives/lo-ch-05.qmd >}}

**Readings**

{{< include readings/readings-ch-03.qmd >}}

{{< include readings/readings-ch-05.qmd >}}

### Week 4

**Virtual Environments:
[uv](lectures/7a-virtual-environments-uv.qmd) and
[renv](lectures/7b-virtual-environments-renv.qmd)**

{{< include learning_objectives/lo-ch-07.qmd >}}

**[Organization of Data Science Projects](lectures/8-regex-filenames-project-organization.qmd)**

{{< include learning_objectives/lo-ch-08.qmd >}}

**[Introduction to Regular Expressions (RegEx)](lectures/8b-regex.qmd)**

{{< include learning_objectives/lo-ch-08b.qmd >}}

**[Asking Effective Questions](lectures/8c-asking_questions.qmd)**

{{< include learning_objectives/lo-ch-08c.qmd >}}

**Readings**

{{< include readings/readings-ch-07.qmd >}}

{{< include readings/readings-ch-08.qmd >}}

## Attributions

Materials were inspired, re-used and re-mixed from the following sources:
- [Software Carpentry](https://software-carpentry.org/), specifically the Unix Shell and Git lessons
- [Happy Git and GitHub for the useR by Jenny Bryan and the STAT 545 TAs](http://happygitwithr.com/)
- [Data 8: The Foundations of Data Science](http://data8.org/), specifically Lab 01
- [Data Carpentry Reproducible Science Workshop](https://datacarpentry.org/rr-organization1/)

## License

The UBC Master of Data Science DSCI 521: Computing Platforms for Data Science course materials here are licensed under the Creative Commons Attribution 2.5 Canada License ([CC BY 2.5 CA](https://creativecommons.org/licenses/by/2.5/ca/)). If re-using/re-mixing please provide attribution and link to this webpage.
