[project]
name 3 "dsci-521-platforms-dsci-book"
version = "2026.08.27.9000"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "jupyterlab>=4.6.3",
    "jupyterlab-rise>=0.43.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "otter-grader>=7.0.0",
    "rpy2>=3.6.7",
]
