name: Check Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "5 8 * * Sun" # once a week every sunday at 8:05
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: '--cache --max-cache-age 7d https://ubc-mds.github.io/DSCI_521_platforms-dsci_book/'
          fail: true
